spring.application.name=Sharecycle-backend

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/cycle
spring.datasource.username=username
spring.datasource.password=Password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Upload folder
app.upload.dir=uploads

# Multipart limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

# PayPal (optional, keep if you use it)
paypal.client.id=ASC7o9L-ft-ecQbCXoEhRyor52LOL6tHDohfny89aFDgeN_CzWNOYnQ5o8YLB_dh1qvatW0D9rFxvxK2
paypal.client.secret=EAO6HhhcpEeXH4WPGy9pTkttIz3GCt9zTVRX4OMXgCvkcWEjl6_fEK1l8tvHyFrASHEXEmS0rxAiVRWr

# Mail
spring.mail.username=mostafatarek7000@gmail.com
spring.mail.password=arkr tozx bqoj lonp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Firebase
firebase.config.path=firebase-service-account.json

